/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RegistrationId = IDL.Nat;
export const Registration = IDL.Record({
  'id' : RegistrationId,
  'interests' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const RegistrationInput = IDL.Record({
  'interests' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const SubmitResult = IDL.Variant({
  'ok' : RegistrationId,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'getRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'submitRegistration' : IDL.Func([RegistrationInput], [SubmitResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RegistrationId = IDL.Nat;
  const Registration = IDL.Record({
    'id' : RegistrationId,
    'interests' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RegistrationInput = IDL.Record({
    'interests' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SubmitResult = IDL.Variant({ 'ok' : RegistrationId, 'err' : IDL.Text });
  
  return IDL.Service({
    'getRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'submitRegistration' : IDL.Func([RegistrationInput], [SubmitResult], []),
  });
};

export const init = ({ IDL }) => { return []; };